<a href="https://colab.research.google.com/github/AkulRastogi/PythonML/blob/master/NumPY_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]
np_array = np.array(mylist)

In [3]:
type(np_array)

numpy.ndarray

In [4]:
mymatrix = [[1,2,3], [4,5,6], [7,8,9]]
np_matrix = np.array(mymatrix)

In [5]:
type(np_matrix)

numpy.ndarray

In [6]:
np_array

array([1, 2, 3])

In [7]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 9000, 3345)

array([   0, 3345, 6690])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((2,3,4), dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [17]:
np.ones((2,3,4, 5), dtype = int)

array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])

In [24]:
np.linspace(0, 10, 2, dtype = int)

array([ 0, 10])

In [25]:
np.linspace(0, 0, 2)

array([0., 0.])

In [27]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [28]:
np.eye(9, dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [29]:
np.random.rand(7)

array([0.16617105, 0.30683786, 0.54315329, 0.47462374, 0.93473763,
       0.18056559, 0.00735558])

In [31]:
np.random.rand(2,2)

array([[0.24186977, 0.12204565],
       [0.4947004 , 0.44180758]])

In [34]:
np.random.randn(10)

array([ 0.71118109,  0.02991723,  0.10256724,  0.28004208, -0.43596257,
       -0.45508682, -1.11157804, -1.25393274,  0.42384235,  0.07417379])

In [35]:
np.random.randint(0, 1000)

830

In [36]:
np.random.randint(0, 10000, 10)

array([5284, 6741, 3415, 8505, 6524, 1328, 2416,  407, 7120, 5650])

In [54]:
np.random.seed(42)

In [55]:
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [43]:
np.random.rand(4,5)

array([[0.72087685, 0.24776828, 0.62277995, 0.14244882, 0.20117628],
       [0.08121773, 0.95347229, 0.05573827, 0.59953648, 0.72299763],
       [0.97028972, 0.82156946, 0.52755107, 0.33147673, 0.3539822 ],
       [0.0790303 , 0.55591438, 0.16579446, 0.29523783, 0.84060849]])

In [58]:
np.random.seed(40)
print(np.random.rand(4))
print(np.random.rand(4))

[0.40768703 0.05536604 0.78853488 0.28730518]
[0.45035059 0.30391231 0.52639952 0.62381221]


In [60]:
np.random.seed(40)
print(np.random.rand(4))
np.random.seed(40)
print(np.random.rand(4))

[0.40768703 0.05536604 0.78853488 0.28730518]
[0.40768703 0.05536604 0.78853488 0.28730518]


In [63]:
np.random.seed(40)
print(np.random.rand(5))
print(np.random.rand(4))
np.random.seed(40)
print(np.random.rand(4))
print(np.random.rand(3))

[0.40768703 0.05536604 0.78853488 0.28730518 0.45035059]
[0.30391231 0.52639952 0.62381221 0.77677546]
[0.40768703 0.05536604 0.78853488 0.28730518]
[0.45035059 0.30391231 0.52639952]


In [64]:
import random as rd

In [71]:
print(rd.randint(1,2))
print(np.random.randint(1,2))

2
1


In [78]:
arr = np.arange(30, 60).reshape(3, 10)

In [79]:
arr.max()

59

In [80]:
arr.min()

30

In [81]:
arr.argmax()

29

In [82]:
arr.argmin()

0

In [83]:
arr.shape

(3, 10)

In [84]:
arr.dtype

dtype('int64')